/// Artifact entity representing generated documents, code, or analyses.
///
/// Artifacts are embedded within assistant messages and can be
/// opened in a dedicated viewer for export (DOCX, PDF, etc.).
library;

/// Type classification for artifacts.
enum ArtifactType {
  /// Text documents: contracts, letters, reports, tables.
  document,

  /// Executable code: HTML+JS, React, Python.
  code,

  /// Analytical material: legal analysis, expertise, audit.
  analysis,

  /// Image content.
  image;

  /// Creates an [ArtifactType] from its server-side string representation.
  static ArtifactType fromString(String value) => switch (value.toUpperCase()) {
        'DOCUMENT' || 'CONTRACT' || 'CLAIM' || 'COMPLAINT' => ArtifactType.document,
        'CODE' => ArtifactType.code,
        'ANALYSIS' => ArtifactType.analysis,
        'IMAGE' => ArtifactType.image,
        _ => ArtifactType.document,
      };

  /// Returns the Russian label for this artifact type.
  String get label => switch (this) {
        ArtifactType.document => 'Документ',
        ArtifactType.code => 'Код',
        ArtifactType.analysis => 'Анализ',
        ArtifactType.image => 'Изображение',
      };

  /// Returns the icon name for display.
  String get iconName => switch (this) {
        ArtifactType.document => 'description',
        ArtifactType.code => 'code',
        ArtifactType.analysis => 'analytics',
        ArtifactType.image => 'image',
      };
}

/// An artifact generated by the AI assistant.
///
/// Artifacts represent structured content (documents, code blocks,
/// analyses) that can be viewed, edited, and exported independently
/// from the chat message stream.
class Artifact {
  const Artifact({
    required this.id,
    required this.type,
    required this.title,
    required this.content,
    this.language,
  });

  /// Unique identifier for this artifact.
  final String id;

  /// The type of artifact content.
  final ArtifactType type;

  /// Human-readable title for the artifact.
  final String title;

  /// The full content (Markdown for documents, source code for code).
  final String content;

  /// Programming language (for code artifacts only).
  final String? language;

  /// Creates a copy with modified fields.
  Artifact copyWith({
    String? id,
    ArtifactType? type,
    String? title,
    String? content,
    String? language,
  }) =>
      Artifact(
        id: id ?? this.id,
        type: type ?? this.type,
        title: title ?? this.title,
        content: content ?? this.content,
        language: language ?? this.language,
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Artifact && runtimeType == other.runtimeType && id == other.id;

  @override
  int get hashCode => id.hashCode;

  @override
  String toString() => 'Artifact(id=$id, type=$type, title=$title)';
}
